### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by ryan0233** [temp010/web-app#15]
We accomplished all of our weekly goals for Sprint 2.

**Comment by gus-quintini** [comment]
I took time in class to work on the deadlines with my team members. We then split the group work evenly to completely all the tasks. The only thing that went wrong was that the logo took a little longer than expected

**Comment by gus-quintini** [comment]
@thomasjbradley

**Comment by ryan0233** [comment]
I think our team overall succeeded in properly delegating and completing all of our tasks this week. I successfully accomplished my part of the competitive analysis, and contributed to the work during our team's meet-ups along with everyone else.
Our group was less successful in the logo design, which took longer than expected and needed a bit of extra time to be completed.

**Comment by kiri-jurschewsky** [comment]
I did some work in class, at home, and in a team meeting. In class, the workload was divided evenly as to optimize workflow and time. Everything was done on time. Logo took a bit longer than we had planned and expected.

**Comment by thomasjbradley** [comment]
Amazing Sprint reviews—thanks!

---

The Sprint 2 Issues aren’t detailed enough—some of them I don’t even know what their purpose is, like "Weather Bug" or "Apple Weather". What are the purpose of those Issues and what was the associated task?
